### ISSUE TITLE
Login UI - ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by ruizehung** [edgedb/edgedb-ui#404]
## ReferenceError: Buffer is not defined

My OS: Mac 15.1.1

I run Edgedb locally in docker container via docker compose with the following config
```
edgedb:
    image: edgedb/edgedb:6.0-beta.2
    restart: unless-stopped
    environment:
      EDGEDB_SERVER_INSTANCE_NAME: Local Dev
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_ADMIN_UI: enabled
      EDGEDB_SERVER_USER: edgedb
      EDGEDB_SERVER_PASSWORD: ......
    ports:
      - "5656:5656"
    volumes:
      - edgedb-data:/var/lib/edgedb/data
```

I was able to connect to the instance via `edgedb instance link` CLI
```
node ➜ /workspace (main) $ edgedb instance list
┌────────┬──────┬─────────────┬────────────────────┬────────┐
│ Kind   │ Name │ Location    │ Version            │ Status │
├────────┼──────┼─────────────┼────────────────────┼────────┤
│ remote │ dev  │ edgedb:5656 │ 6.0-beta.2+0b7b503 │ up     │
└────────┴──────┴─────────────┴────────────────────┴────────┘
node ➜ /workspace (main) $ edgedb -I dev
EdgeDB 6.0-beta.2+0b7b503 (repl 6.1.1+b8ebf1f)
Type \help for help, \quit to quit.
dev:main> select 1 + 2;
{3}
dev:main> 
```

But I cannot logged into the UI even with correct user name and password.
### On Arc browser: Version 1.79.1 (58230), Chromium Engine Version 132.0.6834.160
<img width="1727" alt="Image" src="https://github.com/user-attachments/assets/2684e288-1b84-4478-b552-8b0a0e7e48f2" />

<img width="1727" alt="Image" src="https://github.com/user-attachments/assets/ddbbd21c-85bc-46f1-a593-029872c2e550" />

### On Safari browser: Version 18.1.1 (20619.2.8.11.12)

<img width="1727" alt="Image" src="https://github.com/user-attachments/assets/5397f203-4d29-4ae2-b47b-5d97e1fd1f79" />
