### ISSUE TITLE
Unable to use the UI if running edgedb without password

### ISSUE THREAD

**Issue by alexgorbatchev** [edgedb/edgedb-ui#70]
my k8s edgedb deployment has, no password configured

```yaml
      containers:
        - name: edgedb
          image: edgedb/edgedb:2.2
          env:
            - name: EDGEDB_SERVER_SECURITY
              value: insecure_dev_mode
            - name: EDGEDB_SERVER_ADMIN_UI
              value: enabled
```

The UI login button remains disabled and I'm unable to login

![image](https://user-images.githubusercontent.com/65633/192064118-4725f506-5be2-4df2-9b77-6411b135d5aa.png)

```
➜ edgedb --version                                                               
EdgeDB CLI 2.0.5+f78cf34
```

What am I doing wrong?
